model:
  backbone: "resnet50"
  avg_output: True 
  is_sym: False # If the encoder and decoder are symmetric

data:
  bs: 64
  nw: 8
  imsize: 128
  hand_img_size: 128
  contact: True # Default True
  EPIC55_only: True
  data_dir: /home/mohit/EPIC-KITCHENS
  filtered_dir: /data11/mc48/renders/mohit/inpaint_4f_best_passthrough # inpaint_4f_passthrough_nested, inpaint_4f_best_passthrough
  # annot_dir: /home/mohit/VOS/epic-affordances/training/scripts/generate_metadata
  # annot_dir: /home/mohit/VOS/epic-affordances/training/scripts/generate_metadata/nosup
  annot_dir: /home/adityap9/projects/hands-as-probes/ACP/datasets/ACP_metadata
  hand_seg_dir: /data02/mohit/VOS/video-hand-grasps/src_segmentation/inferred_masks/epic/SegNetFCNMultiHead_Egohandsfull
  use_preset: True
  preset_indices_path: /home/adityap9/projects/hands-as-probes/ACP/debug/sampled_indices_1k_hand_filtered.txt # sampled_indices_100k_hand_filtered.txt
  preset_val_indices_path: /home/adityap9/projects/hands-as-probes/ACP/debug/sampled_val_indices_hand_filtered.txt
  use_img_input: True

training:
  lr: 0.0001
  decay: 0.0001
  num_epochs: 400
  num_batches: 256
  save_after: 5 # num_valsteps
  replace: False
  log_interval: 1
  ckpt_interval: 5
  resume: False
  pos_weight: 4
  flips: True # Default True
  motionblur: True # Default True
  negres_fixed: False # Default False
  hand_mask: True # Default True
  obj_mask: True # Default True
  obj_sample: True # Default True
  obj_thresh: 0.8 # Default 0.8
  length_based_sampling: True # Default True
  masking: True # Default True
  bbshift: 0. # Default 0.
  mask_location: bc # Default bc
  use_class_loss: True # Default True
  hand_ckpt: /home/adityap9/projects/hands-as-probes/ACP/models/GUN-71/GUN71_tsc_seed0_checkpoint_27.pth
  bottomkclass: 15 # Default 15
  topkclass: 1 # Default 1
  use_no_hands: True # Default False
  use_hand_segmask: False # Default False
  # loss_masking: True # Only applicable when is_sym set to true
  use_only_grasp: False # Default False